
env2gcp:
  straas-staging: straasio-staging
  straas-production: straasio-production
  lh-production: ikalacomputeenginetest
  lh-alpha: ikalacomputeenginetest

credential:
  slack_token: xoxb-18018736162-4VAqjSsuouE7jW5wRk3GXFBz
  pagerduty_token: WG2G-xnojDhQPrp8sY47
  gcp:
    straasio-staging:
      email: gcpservieaccount@straasio-staging.iam.gserviceaccount.com
      scopes:
        - https://www.googleapis.com/auth/cloud-platform
        - https://www.googleapis.com/auth/monitoring.read
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAoj2OEKMm5FqW+VYUlg8W8H++MZzIbzVETMwqGLzI/+9z72UN
        pzoZgbB0zaay5kzAOiuboGyfBbbMRKg4T/RTJoH+Filkyf82bg1xvziFb4U7H5NB
        blHMQBgihZxkmHhjbv3SeoKihjz1PdpK1enBE5u17H8oj46toMVwF/N1kJ9si7Zd
        jcgEe0jZPtJL45cp4BDtPkJ0u3veq8/S2MN0BdN6uTgSj8pt+yQZpg70NzYxLAOz
        ltsI2+EW1AFVu2bMj3imDFYg7q0Cr8oq76dBLy/XJYLdPnDQGOFMfKIZbzf4wKib
        ZofqrrYMvl4QEIoTb3M/hMQ9t4z83YlAYkDRowIDAQABAoIBABpcuC3Z5OLsGWYQ
        Z63ua8LObwAuwp7XX+6+qgR1AJAdv4/hsrM+jJB3NLOJ573mMMIC/fm2TKyoBE8P
        qn7La4txSfEd7sOn1ZdSVe5FZ+E0G+RIkDQ11GOByHI/dFUWEsohMkc33OLFGvBe
        /RP/NKFUBt6T1upku6/JBSrPI4ZJLyRGWewES7HsION6pRmssgKtdrmBDsQRyO/y
        RL+QtEnM3JAllYzjB73wxC3UUHJtyQBUkZ+XGn+Iu9GYoMlPvHG2pdAtGQpDrRQ6
        z+DmDlmoMLHsx0FFhGPihr2GM3IfgTJzsaQrr0dI26HS6/Unslqf8CNCQAtllBd0
        ARM3K1kCgYEAzsKtgBspoWnnFor2ZVRvylUH1hMmF7JzQ1czaZ3OYhm4YPZXt6Sf
        IagsBFeUwX7Hzm1sXOq5yLQqqcgi7FpuUfmHI5cjebUp9TmA9vZa5EQFL9el8+Jw
        Q02cGXWV70ZaphCqvEUZSfvl6MuJ0absCR4fanP5+88QgRPuRbKb/YUCgYEAyOCt
        jpzBWQm90EU9LQMgdRLlq5EkGQYKGNlOSfuHhiqtit5NYgwQ0LAim1aXR5faBpK0
        bYfJyqg/d+2wJltz9AYot2XQhHp5bavyCDRLJ61lNMBs4bapae03bvtLICzhYMad
        o1KiQSQV257SFeEs+AQCJpRyYndvonFaWPcJRwcCgYEAwxgA/IMk2hECo0vGSUDO
        Jx3qwf3ZkLyqdB1A/uSPjBN23c80X60vFmQH/KTjUV0ejdLEUDyPxyjxpLia82g0
        9pa8BEIlkD74c1KqNN2qT/864bTa+3Bru6XsqD1Cl79L46yQXgvZW+0bOHlt9uxJ
        hiTtQdZjSE5O5Wz4BL4O4L0CgYEAnwFZ4F0snvIbEdT8y7iB5KoEqn3E+RnSvECm
        u+EiMY1uuVGmJ0ottUL24cb1EHKe3j0aHOkzTftH4gJ/QJ17d1m4uRMarwLTQ4Cr
        oNrj8pBKYCtBBJm2GGbxTiQUH2/nJteQyEsMrEuIEcPxv+fx1JA3s5olwNORxh+7
        yFgjO9kCgYAS5anLqFrPafTLs4PubPhGa3WF8qakWKk9yZCiwMVRqcu4uYI7v09L
        Z4pw58OfFMXIy15qduoTPVqAdSYxuM+BrL5fMjU4RPxPwkbMpVYNEI01dK/RdUym
        6vlMZOywmP9CIwo/7cU63aVnnbXoaHxPRj+lEEITUed+oYA37I5wEw==
        -----END RSA PRIVATE KEY-----
    straasio-production:
      email: gcpservieaccount@straasio-production.iam.gserviceaccount.com
      scopes:
        - https://www.googleapis.com/auth/cloud-platform
        - https://www.googleapis.com/auth/monitoring.read
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAgKYATVX6U5ZLTxXohvJ7ORQ/bl2dJWGD4FBZWARcY/WNPbcc
        9qPse89qCuUWA5TWzXg89neeFYBZ/5tvgvlK0UuF8rJtkiVoGzqyyec4kQFG748+
        cNyZZ3ORTYJlQsOdy8j/C7koRqfLelnqANAAqIV8lESU0S0B6eWddXHXIpfhJqye
        sOW+u9qNBIyJZV9UfvXvE6EwzWXZi46OkqL/620YB7epYyY2PTjhutg8ru8VKXsa
        RoGjPXjGda22gxvxlaRur4En/YvIEr0lDyZV5Ux2C63DvKd3m0oJORrv78tFvh/v
        JzaI7BBwUZ6z3Ygzcy1AgFRAuZmofBbLSsXXcQIDAQABAoIBACdosrb+G4z3gWJc
        p7qPFUhK95NrgfQthyRz+KqJy3OjiPza1ziGxq62vxlPTAsU0ShoKOSnh/m2M9ul
        VeedTloG9KWAGyil5NpShOpstltVNNG1477XFPcn498GjtaA7hm7HMYOllPumtqE
        KLbPASSen6cbyyq4ytlHyZBsqyahSNUENjf8luaZKmHO0QZ/q5Q4y6NhltKIoa4K
        s5qfeSBxD/V81lXLEYqKJqlCZGWG5NlAuSCOX9Y1mg5x1ReizZR8CHLDqluuChiO
        ET4snOgIiHWtxJD7JQHl5XOgI/pmOJUipugCcgCc/CaAbOcswwnU0EEs1sQcpvmj
        x5liCDECgYEAuYPaNyjWJcWXxx93bIHwp+bfVJyvagkCF3PsdNzfuCAPCzw7b3jW
        1fBianvdxFfFOmF80dZvxqPRQEMf8gUAQ6Lolh0kO2yHfEm2nD5lDAC4MRis9cDx
        qymW0LIU3vHkL/9w73hhufC+MrOhH+BHZUUeFAOGbusPs7d3+hoyhK8CgYEAsYcC
        nXFGv9bKB2ZeKydC/IWrmB24D3MKstu/QUYfP24zwsCcXMUb0UIhYOmuwXv/voWd
        PSYrDcNB0INMSBHf1W+gmMdBQ7GArW3TC9jkcZFEilcmn2EqRXfv0w6G3K2XRfQy
        5nOyqORhooOP3xNRTZx9Ug2/5UduUooHuJcGrd8CgYEAhVQS+AO8bOcm3zBpRy3Y
        RQOzzH7Tv1R8EVj6Pz8i9pTr2vpOCR6C4L1kLf2Z8+vUztGTwMfqC4xe7l2PzwPz
        HakumfyVtrOYaCYePQrG2qqFtptyaylhRs+cGZ9zSov0oN5oT2NocRdpysy450zs
        Ywcax+2Ep6D+5v3cF37OgfcCgYEAi+/ss8azCk15e1PKLyIHv55uoL3sdOEuMcbe
        f8mSoCFyU7YYi1gkkVMblJUf2Ayyj7ArPiR0E6kym/ajjrvoQQp5AXUvkPi+gfbs
        QY56pLrp2FLScxfYhmIAfdIZpKKBd/cCmH3i+xbrj3s9UY6crB0K/D8yYL1pzU5Y
        v7zs2ukCgYAM16TsCBJCEz+alKtXXxMlvj+99cgZ7t1l1EzR8lmV2C/hacYKdDq8
        86xJVDnJL/EExCtefd2c8IUbZbJHggW2yL8qgjELpy01WSk0x0jQdbukpmReNcpJ
        nGLpp9m/p46p74c3LIhm1xmF6d9qqjYGj5iWoSvRFG0piovSOxLnVg==
        -----END RSA PRIVATE KEY-----
