interval: 1m
script: |
  v400 = mquery("record", "req.create.record.s400", "value", "sum", "5m", "0m")
  v500 = mquery("record", "req.create.record.s500", "value", "sum", "5m", "0m")
  v = v400 + v500
  alert(
    "fail_rate",
    notify("backend-data"),
    lastFor(v, ">", 10, "1m"),    // P0
    lastFor(v, ">", 1, "1m")     // P1
  )
