interval: 1m
script: |
  v200 = mquery("record", "req.get.record.s200", "value", "sum", "5m", "0m")
  v400 = mquery("record", "req.get.record.s400", "value", "sum", "5m", "0m")
  v401 = mquery("record", "req.get.record.s401", "value", "sum", "5m", "0m")
  v403 = mquery("record", "req.get.record.s403", "value", "sum", "5m", "0m")
  v404 = mquery("record", "req.get.record.s404", "value", "sum", "5m", "0m")
  v500 = mquery("record", "req.get.record.s500", "value", "sum", "5m", "0m")
  v502 = mquery("record", "req.get.record.s502", "value", "sum", "5m", "0m")
  v = (v400 + v401 + v403 + v404 + v500 + v502) / (v200 + v400 + v401 + v403 + v404 + v500 + v502)
  alert(
    "fail_rate",
    notify("backend-data"),
    lastFor(v, ">", 0.6, "30m"),    // P0
    lastFor(v, ">", 0.5, "10m")     // P1
  )
