interval: 1m
script: |
  vAll = mquery("record", "req.create.record.proc_time", "count", "sum", "5m", "0m")
  v200 = mquery("record", "req.create.record.s200", "value", "sum", "5m", "0m")
  v = vAll - v200
  alert(
    "fail_rate",
    notify("backend-data"),
    lastFor(v, ">", 10, "1m"),    // P0
    lastFor(v, ">", 1, "1m")     // P1
  )
