language: go

go:
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:
  make deps

script:
  - PATH="$HOME/gopath/bin:$PATH"
  - sh scripts/coverage --coveralls

