interval: 2m
script: |
  filter = [
    'metric.type="pubsub.googleapis.com/subscription/num_outstanding_messages"',
    'resource.label.subscription_id="sub-revealer"'
  ].join(" AND ")
  v = squery(filter, "avg", "5m", "0m")
  alert(
    "outstanding",
    notify("backend-data"),
    lastFor(v, ">", 1000, "30m"),  // P0
    lastFor(v, ">", 1000, "10m")   // P1
  )
