interval: 1m
script: |
  v = mquery("revealer-collector", "sys.cpu_usage", "value", "count", "5m", "0m")
  alert(
    "absence",
    notify("backend-data"),
    lastFor(v, "=", 0, "15m"),  // P0
    lastFor(v, "=", 0, "5m")    // P1
  )
