interval: 1m
script: |
  sum = mquery("revealer-syncer", "syncjob.proc_time", "value", "sum", "5m", "0m")
  count = mquery("revealer-syncer", "syncjob.proc_time", "count", "sum", "5m", "0m")
  v = count == 0 ? 0 : sum / count
  console.log(sum, count, v)
  alert(
    "proc_time",
    notify("backend-data"),
    lastFor(v, ">", 15000, "30m"),  // P0
    lastFor(v, ">", 10000, "10m")   // P1
  )
