interval: 1m
script: |
  vAll = mquery("message", "req.add.msg.proc_time", "count", "sum", "5m", "0m")
  v200 = mquery("message", "req.add.msg.s200", "value", "sum", "5m", "0m")
  v = vAll == 0 ? 0 : (vAll - v200) / vAll
  alert(
    "fail_rate",
    notify("backend-data"),
    lastFor(v, ">", 0.3, "30m"),    // P0
    lastFor(v, ">", 0.1, "10m")     // P1
  )
