interval: 5m
script: |
  v = mquery("revealer-collector", "rest.s5XX.err", "value", "avg", "5m", "1m")
  alert(
    "cpu",
    notify("backend"),
    lastFor(v, ">", 50, "0m"),
    lastFor(v, ">", 5,  "0m")
  )
