package core

import (
	"fmt"
	"testing"
	"time"

	"github.com/coreos/etcd/client"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/suite"

	etcdMocks "straas.io/external/mocks"
	"straas.io/pierce"
	"straas.io/pierce/mocks"
)

// roomMock is an autogenerated mock type for the roomMock type
type roomMock struct {
	mock.Mock
}

// Empty provides a mock function with given fields:
func (_m *roomMock) Empty() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Join provides a mock function with given fields: _a0
func (_m *roomMock) Join(_a0 pierce.SocketConnection) {
	_m.Called(_a0)
}

// Leave provides a mock function with given fields: _a0
func (_m *roomMock) Leave(_a0 pierce.SocketConnection) {
	_m.Called(_a0)
}

// Start provides a mock function with given fields:
func (_m *roomMock) Start() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *roomMock) Stop() {
	_m.Called()
}

func TestCore(t *testing.T) {
	suite.Run(t, new(coreTestSuite))
}

type coreTestSuite struct {
	suite.Suite
	impl     *coreImpl
	etcdMock *etcdMocks.Etcd
}

func (s *coreTestSuite) SetupTest() {
	s.etcdMock = &etcdMocks.Etcd{}
	s.impl = NewCore(s.etcdMock, "/pierce").(*coreImpl)
}

func (s *coreTestSuite) TestGet() {
	resp := &client.Response{
		Action: "get",
		Node: &client.Node{
			Key:   "/pierce/47/bc/aaa/bbb",
			Dir:   false,
			Value: "1234",
		},
	}
	s.etcdMock.On("Get", "/pierce/47/bc/aaa/bbb", true).Return(resp, nil).Once()

	v, err := s.impl.Get("aaa", "bbb")
	s.NoError(err)
	s.Equal(v, float64(1234))
	s.etcdMock.AssertExpectations(s.T())
}

func (s *coreTestSuite) TestGetAll() {
	resp := &client.Response{
		Action: "get",
		Node: &client.Node{
			Key:   "/pierce/47/bc/aaa",
			Dir:   false,
			Value: "1234",
		},
	}
	s.etcdMock.On("Get", "/pierce/47/bc/aaa", true).Return(resp, nil).Once()

	v, err := s.impl.GetAll("aaa")
	s.NoError(err)
	s.Equal(v, float64(1234))
	s.etcdMock.AssertExpectations(s.T())
}

func (s *coreTestSuite) TestSet() {
	s.etcdMock.On("RefreshTTL", "/pierce/47/bc/aaa", roomTTL).Return(nil, nil).Once()
	s.etcdMock.On("SetWithTTL", "/pierce/47/bc/aaa/bbb", "1234", time.Minute).Return(nil, nil).Once()
	s.etcdMock.On("IsNotFound", error(nil)).Return(false).Once()

	err := s.impl.Set("aaa", "bbb", 1234, time.Minute)
	s.NoError(err)
	s.etcdMock.AssertExpectations(s.T())
}

func (s *coreTestSuite) TestSetFirstTime() {
	someErr := fmt.Errorf("some err")
	s.etcdMock.On("RefreshTTL", "/pierce/47/bc/aaa", roomTTL).Return(nil, someErr).Once()
	s.etcdMock.On("RefreshTTL", "/pierce/47/bc/aaa", roomTTL).Return(nil, nil).Once()
	s.etcdMock.On("SetWithTTL", "/pierce/47/bc/aaa/bbb", "1234", time.Minute).Return(nil, nil).Once()
	s.etcdMock.On("IsNotFound", someErr).Return(true).Once()

	err := s.impl.Set("aaa", "bbb", 1234, time.Minute)
	s.NoError(err)
	s.etcdMock.AssertExpectations(s.T())
}

func (s *coreTestSuite) TestSetError() {
	someErr := fmt.Errorf("some err")
	s.etcdMock.On("RefreshTTL", "/pierce/47/bc/aaa", roomTTL).Return(nil, someErr).Once()
	s.etcdMock.On("IsNotFound", someErr).Return(false).Once()

	err := s.impl.Set("aaa", "bbb", 1234, time.Minute)
	s.Error(err)
	s.etcdMock.AssertExpectations(s.T())
}

func (s *coreTestSuite) TestSetError2() {
	someErr := fmt.Errorf("some err")
	s.etcdMock.On("RefreshTTL", "/pierce/47/bc/aaa", roomTTL).Return(nil, nil).Once()
	s.etcdMock.On("SetWithTTL", "/pierce/47/bc/aaa/bbb", "1234", time.Minute).Return(nil, someErr).Once()
	s.etcdMock.On("IsNotFound", error(nil)).Return(false).Once()

	err := s.impl.Set("aaa", "bbb", 1234, time.Minute)
	s.Error(err)
	s.etcdMock.AssertExpectations(s.T())
}

func (s *coreTestSuite) TestSetError3() {
	someErr := fmt.Errorf("some err")
	s.etcdMock.On("RefreshTTL", "/pierce/47/bc/aaa", roomTTL).Return(nil, someErr).Twice()
	s.etcdMock.On("SetWithTTL", "/pierce/47/bc/aaa/bbb", "1234", time.Minute).Return(nil, nil).Once()
	s.etcdMock.On("IsNotFound", someErr).Return(true).Once()

	err := s.impl.Set("aaa", "bbb", 1234, time.Minute)
	s.Error(err)
	s.etcdMock.AssertExpectations(s.T())
}

func (s *coreTestSuite) TestJoin() {
	maintain := make(chan time.Time)
	rooms := []*roomMock{}

	c1 := &mocks.SocketConnection{}
	c2 := &mocks.SocketConnection{}
	c1.On("RoomIds").Return([]string{"aaa", "bbb"}).Once()
	c2.On("RoomIds").Return([]string{"bbb", "ccc"}).Once()

	s.impl.rFactory = func(roomID, etcdKey string) Room {
		room := &roomMock{}
		rooms = append(rooms, room)

		switch roomID {
		case "aaa":
			room.On("Join", c1).Return().Once()
		case "bbb":
			room.On("Join", c1).Return().Once()
			room.On("Join", c2).Return().Once()
		case "ccc":
			room.On("Join", c2).Return().Once()
		}
		room.On("Start").Return().Once()
		return room
	}

	s.impl.Join(c1)
	s.impl.Join(c2)
	s.impl.loopOnce(maintain)
	s.impl.loopOnce(maintain)

	s.Equal(s.impl.rooms, map[string]Room{
		"aaa": rooms[0],
		"bbb": rooms[1],
		"ccc": rooms[2],
	})
	for _, room := range rooms {
		room.AssertExpectations(s.T())
	}
}

func (s *coreTestSuite) TestLeave() {
	maintain := make(chan time.Time)

	c1 := &mocks.SocketConnection{}
	c1.On("RoomIds").Return([]string{"aaa", "bbb"}).Once()

	roomA := &roomMock{}
	roomB := &roomMock{}
	roomC := &roomMock{}

	roomA.On("Leave", c1).Return().Once()
	roomB.On("Leave", c1).Return().Once()

	s.impl.rooms = map[string]Room{
		"aaa": roomA,
		"bbb": roomB,
		"ccc": roomC,
	}
	s.impl.Leave(c1)
	s.impl.loopOnce(maintain)

	roomA.AssertExpectations(s.T())
	roomB.AssertExpectations(s.T())
	roomC.AssertExpectations(s.T())

}

func (s *coreTestSuite) TestMaintain() {
	maintain := make(chan time.Time, 1)

	roomA := &roomMock{}
	roomB := &roomMock{}
	roomC := &roomMock{}

	roomA.On("Empty").Return(true).Once()
	roomB.On("Empty").Return(false).Once()
	roomC.On("Empty").Return(true).Once()
	roomA.On("Stop").Return().Once()
	roomC.On("Stop").Return().Once()

	s.impl.rooms = map[string]Room{
		"aaa": roomA,
		"bbb": roomB,
		"ccc": roomC,
	}
	maintain <- time.Now()
	s.impl.loopOnce(maintain)

	roomA.AssertExpectations(s.T())
	roomB.AssertExpectations(s.T())
	roomC.AssertExpectations(s.T())

	s.Equal(s.impl.rooms, map[string]Room{
		"bbb": roomB,
	})
}
