# must with glibc
FROM frolvlad/alpine-glibc:alpine-3.3
MAINTAINER taco.lin@livehouse.in

# install bash
RUN apk add --update bash && rm -rf /var/cache/apk/*

COPY build/sauron /build/sauron
COPY config/sauron /config/

ENTRYPOINT ["/build/sauron"]
