package mocks

import "straas.io/sauron"
import "github.com/stretchr/testify/mock"

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

// LoadConfig provides a mock function with given fields: key, v
func (_m *Config) LoadConfig(key string, v interface{}) error {
	ret := _m.Called(key, v)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(key, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadJobs provides a mock function with given fields:
func (_m *Config) LoadJobs() ([]sauron.JobMeta, error) {
	ret := _m.Called()

	var r0 []sauron.JobMeta
	if rf, ok := ret.Get(0).(func() []sauron.JobMeta); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sauron.JobMeta)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
