interval: 1m
script: |
  count = mquery("revealer-collector", "rest.v1.track.proc_time", "value", "count", "5m", "0m")
  alert(
    "absence",
    notify("backend"),
    lastFor(count, "=", 0, "30m"),  // P0
    lastFor(count, "=", 0, "10m")   // P1
  )
