interval: 1m
script: |
  sum = mquery("revealer-syncer", "syncjob.proc_time", "value", "sum", "5m", "1m")
  count = mquery("revealer-syncer", "syncjob.proc_time", "count", "sum", "5m", "1m")
  cputime = squery(
    'metric.type="compute.googleapis.com/instance/cpu/usage_time"',
    "sum", "5m", "1m")
  v = sum / (count + 0.1)
  alert(
    "cpu",
    notify("backend"),
    lastFor(v, ">", 15, "5m"),  // P0
    lastFor(v, ">", 10, "5m")   // P1
  )
