groups:
  - name: backend
    sinkers:
      - type: slack
        token: xoxb-18018736162-pOGrLi9GaD3Vm8tfooE74gnb
        user_name: sauron
        channel: rd-gcloud
        severity: [0, 1, 2]
        recovery: [0, 1, 2]
